name: Docker Image CI

on:
  schedule:
    - cron: '5 4,8 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Trigger dockerhub
      run: curl -X POST https://hub.docker.com/api/build/v1/source/9ae1baa8-4816-4ac0-b753-46b9db1a176e/trigger/2c4e1157-28eb-4c4c-b17f-0926d0a75dee/call/
